language: node_js
node_js:
  - "node"
install:
  - npm install --path admin
  - npm install --path backend
  - npm install --path frontend
script:
  - ./configure && make
  - npm run backend:eslint --path backend
