language: node_js
node_js:
  - node
env:
  matrix:
  - BACKEND_DIR=backend
services: mongodb
script:
  - cd $BACKEND_DIR && npm install && npm run backend:eslint && npm run backend:prettier
  && npm run backend:start &
after_script:
  - npm run backend:test