language: node_js
node_js:
- node
env:
  matrix:
  - BACKEND_DIR=backend
  global:
    secure: GCKMJ6r4W26XI2HMYiowK9LyKbEFFnb4z4XTdQWqVGTYyhlqb8Vn3WOSs8oYYFHPxtwaVcngFUKAN3TlV46qauYDmidjf8XQBA4DWIap8m9SsmhTS1bi4oWpxDnGB5Lt+TliiHJFZiwiGpKdDXp25XOWYICjsRfPhXAYPye+47S13fGM4GFFye1bOeOt2i+WuukcBFhR7GxJQXToJWD0he1nJcmb0THyeNsGo75JkzGJWztLQpDc8OWX1WLbESlDqiaXVf4XAi6+GoigGOzZ30MoZ13V52MdOw0E9pFptkuSqBSuamEwmosp50nIchukn6cJJEF8cQooV1vlHmBHbHCbolQAy03fkyo4L1uRB5ilJd6F0tkW9MKi955dQRbPugMuhJD7ZpthG5i/T6YtYd3zGpDSCHkcuWuFkSY5u2UJ4v5CZOhyatHIwISHfGVWYABOOVAfgTLZjxjaoSXPGR8288O707zEcsjoVhWWEEisg3g42eLt9P3+30J6n0G/MgrlYNdW6AY4MfQiTrvE9bXiibthUBACNKuZLjWlvieBqUXebTHtk58bvQz7S90GVXEV9R0zxskAfSz1XFF/ukZDtB5a+1MXSV2YsTT1r0oz7eHL6nyo0pT7mNLRXUxjeWgNbxsr2cEH9yLm4Gpyq2YOn7A+msB35p/VruAvijE=
services: mongodb
script:
- cd $BACKEND_DIR && npm install && npm run backend:eslint && npm run backend:prettier
  && npm run backend:start && npm run backend:test
