language: node_js
node_js:
  - "node"
install:
  - npm install -g eslint
  - npm install -g prettier
  - npm install --path admin
  - npm install --path backend
  - npm install --path frontend
script:
  - cd backend && npm run backend:eslint && npm run backend:prettier
