export const INTRODUCTION = {
  LOADING: 'INTRODUCTION_IS_LOADING',
  GET_SUCCESS: 'FETCHING_INTRODUCTION_SUCCESS',
  GET_FAILURE: 'FETCHING_INTRODUCTION_FAILURE',
  DELETE_SUCCESS: 'DELETING_INTRODUCTION_SUCCESS',
  DELETE_FAILURE: 'DELETING_INTRODUCTION_FAILURE',
  UPDATE_SUCCESS: 'UPDATING_INTRODUCTION_SUCCESS',
  UPDATE_FAILURE: 'UPDATING_INTRODUCTION_FAILURE',
  ADD_SUCCESS: 'ADDING_INTRODUCTION_SUCCESS',
  ADD_FAILURE: 'ADDING_INTRODUCTION_FAILURE',
  CLEAR: 'CLEAR_INTRODUCTION_FORM',
};

export const SERVICES = {
  LOADING: 'SERVICES_IS_LOADING',
  GET_SUCCESS: 'FETCHING_SERVICES_SUCCESS',
  GET_FAILURE: 'FETCHING_SERVICES_FAILURE',
  DELETE_SUCCESS: 'DELETING_SERVICES_SUCCESS',
  DELETE_FAILURE: 'DELETING_SERVICES_FAILURE',
  UPDATE_SUCCESS: 'UPDATING_SERVICES_SUCCESS',
  UPDATE_FAILURE: 'UPDATING_SERVICES_FAILURE',
  ADD_SUCCESS: 'ADDING_SERVICES_SUCCESS',
  ADD_FAILURE: 'ADDING_SERVICES_FAILURE',
  CLEAR: 'CLEAR_SERVICES_FORM',
};
